backend:
  name: github
  repo: pk31003511-debug/kickcraze-web # Apki GitHub repo ka naam
  branch: master

media_folder: "images"
public_folder: "images"

collections:
  - name: "products"
    label: "Products"
    folder: "products"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Price", name: "price", widget: "number"}
      - {label: "Image", name: "image", widget: "image"}
      - {label: "Description", name: "description", widget: "text"}